- hosts: digio

  vars:
    do_token: {{ digio_ssh_key }}

  tasks:

  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=.ssh/id_rsa